// LANGUAGE-AUDIT (2026-08-16) #11: one-shot scaffold for a new locale.
//
// Adds a 3rd (4th, 5th, …) language to the Voltium Flutter app.
// Reads `lib/l10n/app_en.arb` (the template), copies the structure,
// and writes `lib/l10n/app_<code>.arb` with:
//   - the @@locale header set to the new code
//   - the original EN values as placeholders
//   - a top-of-file `// STUB:` comment that tells translators to
//     replace the EN text with a real translation
//
// After running this script:
//   1. Translate the stub values in `app_<code>.arb`.
//   2. Uncomment the matching `SupportedLanguage` entry in
//      `lib/core/localization/locale_provider.dart`.
//   3. Add `<code>` to `preferred-supported-locales` in `l10n.yaml`.
//   4. Run `flutter gen-l10n` to regenerate `lib/gen/app_localizations*.dart`.
//
// Usage:
//   dart run scripts/scaffold_locale.dart ta
//   dart run scripts/scaffold_locale.dart bn
//   dart run scripts/scaffold_locale.dart mr

import 'dart:convert';
import 'dart:io';

void main(List<String> args) {
  if (args.isEmpty) {
    stderr.writeln(
        'Usage: dart run scripts/scaffold_locale.dart <locale-code>');
    stderr.writeln('Example: dart run scripts/scaffold_locale.dart ta');
    exit(64);
  }
  final code = args.first.toLowerCase().trim();
  if (!RegExp(r'^[a-z]{2,3}$').hasMatch(code)) {
    stderr.writeln('Locale code must be 2-3 lowercase letters (e.g. ta, bn).');
    exit(65);
  }
  if (code == 'en' || code == 'hi') {
    stderr.writeln('Refusing to scaffold built-in locale "$code".');
    exit(65);
  }

  final repoRoot = _findRepoRoot();
  final enPath = File('$repoRoot/lib/l10n/app_en.arb');
  if (!enPath.existsSync()) {
    stderr.writeln('Cannot find app_en.arb at ${enPath.path}.');
    exit(66);
  }
  final outPath = File('$repoRoot/lib/l10n/app_$code.arb');
  if (outPath.existsSync()) {
    stderr.writeln('Refusing to overwrite existing ${outPath.path}.');
    exit(65);
  }

  final enRaw = enPath.readAsStringSync();
  final enJson = jsonDecode(enRaw) as Map<String, dynamic>;
  // Replace the @@locale value with the target code. The rest of the
  // keys stay as-is (English text is the placeholder for translators).
  enJson['@@locale'] = code;
  // Reorder so @@locale is first, then everything else, preserving order.
  final reordered = <String, dynamic>{'@@locale': code};
  enJson.forEach((k, v) {
    if (k != '@@locale') reordered[k] = v;
  });

  // Stash the translator instructions in an `@@_comment` metadata
  // key at the very top. ARB allows `@@*` keys; the leading
  // underscore makes the gen-l10n tool ignore it (it only acts on
  // keys with translations). The translator sees the comment when
  // they open the file.
  reordered['@@_comment'] = _stubComment(code);
  // Move @@_comment to the very first key.
  final firstKey = reordered.keys.first;
  final firstVal = reordered[firstKey];
  reordered.remove(firstKey);
  final finalMap = <String, dynamic>{'@@_comment': reordered['@@_comment']!};
  reordered.remove('@@_comment');
  finalMap.addAll({'@@locale': firstVal});
  reordered.forEach((k, v) => finalMap[k] = v);

  final body = const JsonEncoder.withIndent('  ').convert(finalMap);
  outPath.writeAsStringSync('$body\n');

  stdout.writeln('Wrote ${outPath.path}');
  stdout.writeln('');
  stdout.writeln('Next steps:');
  stdout.writeln('  1. Translate the values in ${outPath.path}');
  stdout.writeln(
      '  2. Uncomment the "$code" entry in lib/core/localization/locale_provider.dart');
  stdout.writeln('  3. Add "$code" to preferred-supported-locales in l10n.yaml');
  stdout.writeln('  4. Run: flutter gen-l10n');
  stdout.writeln('  5. Run: flutter test test/core/i18n_test.dart');
}

/// Walk up from cwd to find the flutter package root (the dir
/// that contains `lib/l10n/app_en.arb`). `dart run` sets cwd to
/// the package root, but allow running from elsewhere.
String _findRepoRoot() {
  var dir = Directory.current.absolute;
  for (var i = 0; i < 6; i++) {
    final probe = File('${dir.path}/lib/l10n/app_en.arb');
    if (probe.existsSync()) return dir.path;
    final parent = dir.parent;
    if (parent.path == dir.path) break;
    dir = parent;
  }
  return Directory.current.path;
}

/// Top-of-file instruction for translators, stored as a `@@_comment`
/// metadata key (the leading underscore is a gen-l10n convention
/// to mark a key as non-translated). The value is multi-line and
/// stays at the very top of the ARB.
String _stubComment(String code) {
  return 'STUB scaffold for locale "$code" — auto-generated by '
      'scripts/scaffold_locale.dart. '
      'All values are currently the English template text. '
      'A translator must replace every value (the text inside the '
      'double-quotes after each key name) with a real $code '
      'translation before this language can be enabled in '
      'LocaleNotifier.supportedLanguages. '
      'The @* metadata blocks (descriptions, placeholders) should '
      'be kept verbatim — they describe the value to gen-l10n and '
      'are not user-visible.';
}
