version: 2
updates:
  # Next.js / Node.js
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "weekly"
    reviewers:
      - "voltium-backend"
    assignees:
      - "voltium-backend"

  # Flutter / Dart
  - package-ecosystem: "pub"
    directory: "/flutter"
    schedule:
      interval: "weekly"
    reviewers:
      - "voltium-mobile"
    assignees:
      - "voltium-mobile"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "voltium-devops"
    assignees:
      - "voltium-devops"
