export enum AdminRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  OPERATIONS_ADMIN = 'OPERATIONS_ADMIN',
  KYC_REVIEWER = 'KYC_REVIEWER',
  FINANCE_ADMIN = 'FINANCE_ADMIN',
  SUPPORT_AGENT = 'SUPPORT_AGENT',
  HUB_MANAGER = 'HUB_MANAGER',
  FLEET_MANAGER = 'FLEET_MANAGER',
  READ_ONLY = 'READ_ONLY',
}

export enum RentalPlanType {
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
  MONTHLY = 'MONTHLY',
}
