/// Abstract repository for rider profile operations.
///
/// EDIT-PROFILE-AUDIT P1-1 (2026-09-08): `updateProfile` and
/// `uploadProfilePhoto` are added so the edit-profile screen
/// has a real seam to fake in tests. Previously the screen
/// called `voltiumApiClientProvider.putRiderProfile` directly
/// and constructed `FilesRepository(ApiClient(),
/// VoltiumApiClient(ApiClient()))` inline per save — two fresh
/// `ApiClient()` instances that threw away the
/// provider-managed client, and no testable surface for the
/// save path.
abstract class RiderRepository {
  /// Fetches the current rider profile data.
  Future<Map<String, dynamic>> getRiderProfile();

  /// Registers a push notification token.
  Future<void> registerFCMToken(String token);

  /// PUTs the rider's profile fields to the server. Thin
  /// pass-through to `VoltiumApiClient.putRiderProfile` so
  /// the screen doesn't depend on the generated client
  /// directly.
  ///
  /// [riderId] is the DB id of the rider whose profile is
  /// being updated. [request] is the typed request body
  /// generated by the screen (name, email, DOB, address,
  /// emergency contact, guarantor fields, profile photo URL).
  /// The rider-scoped audit log + receipts are enforced
  /// server-side.
  Future<void> updateProfile({
    required String riderId,
    required dynamic request,
  });

  /// Uploads a profile photo and returns the URL the rider
  /// should set in the subsequent `updateProfile` call. The
  /// upload creates a `FileRecord` in `PENDING_UPLOAD`; the
  /// server links it to the rider row on the subsequent
  /// PUT. Throws if the upload fails (network, size limit,
  /// unsupported mime).
  ///
  /// [file] is the local file to upload. [category] is the
  /// file-purpose label sent to the server (e.g.
  /// `profile_photo`).
  Future<String> uploadProfilePhoto(
    dynamic file, {
    required String category,
  });

  /// Best-effort delete of an uploaded file (e.g. if the subsequent PUT failed).
  Future<void> deleteUploadedFile(String url);
}
