#!/usr/bin/env bash
# scripts/upload-symbols.sh
# Packaging and upload helper for Flutter release debug symbols generated by
# --obfuscate --split-debug-info=build/symbols/

set -euo pipefail

SYMBOLS_DIR="flutter/build/symbols"
APP_BUNDLE="flutter/build/app/outputs/bundle/release/app-release.aab"
ARCHIVE_NAME="symbols-$(date +%Y%m%d%H%M%S).zip"

echo "==> Verifying Flutter release symbols in $SYMBOLS_DIR"

if [ ! -d "$SYMBOLS_DIR" ] || [ -z "$(ls -A "$SYMBOLS_DIR" 2>/dev/null)" ]; then
  echo "[-] Error: Symbols directory '$SYMBOLS_DIR' is missing or empty."
  echo "    Ensure release build was run with:"
  echo "    flutter build appbundle --release --obfuscate --split-debug-info=$SYMBOLS_DIR --dart-define=API_URL=https://api.voltium.example.com"
  exit 1
fi

echo "[+] Symbols directory found:"
ls -la "$SYMBOLS_DIR"

echo "==> Packaging symbols into $ARCHIVE_NAME"
(cd "$SYMBOLS_DIR" && zip -r "../../$ARCHIVE_NAME" .)

echo "[+] Symbols packaged to flutter/$ARCHIVE_NAME"
echo ""
echo "==> Google Play Console Upload Instructions:"
echo "1. Log into Google Play Console -> App Bundle Explorer"
echo "2. Select your release version -> Downloads tab"
echo "3. Under 'ReTrace mapping file / Native debug symbols', upload 'flutter/$ARCHIVE_NAME'"
echo ""
echo "==> Firebase Crashlytics CLI Upload (optional):"
echo "firebase crashlytics:symbols:upload --app=<FIREBASE_APP_ID> flutter/$ARCHIVE_NAME"
echo ""
echo "[+] Symbol preparation completed successfully."
