// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'rider_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Map<String, dynamic> _$RiderModelToJson(RiderModel instance) =>
    <String, dynamic>{
      'id': instance.id,
      'riderId': instance.riderId,
      'phone': instance.phone,
      'name': instance.name,
      'email': instance.email,
      'fatherName': instance.fatherName,
      'motherName': instance.motherName,
      'dob': instance.dob?.toIso8601String(),
      'currentAddress': instance.currentAddress,
      'profilePhoto': instance.profilePhoto,
      'riderPhoto': instance.riderPhoto,
      'signature': instance.signature,
      'kycStatus': _$KycStatusEnumMap[instance.kycStatus]!,
      'aadhaarFront': instance.aadhaarFront,
      'aadhaarBack': instance.aadhaarBack,
      'panCard': instance.panCard,
      'kycRejectionReason': instance.kycRejectionReason,
      'bankAccount': instance.bankAccount,
      'bankIfsc': instance.bankIfsc,
      'bankName': instance.bankName,
      'bankPassbook': instance.bankPassbook,
      'guarantorName': instance.guarantorName,
      'guarantorRelation': instance.guarantorRelation,
      'guarantorDob': instance.guarantorDob?.toIso8601String(),
      'guarantorPhone': instance.guarantorPhone,
      'guarantorAadhaarFront': instance.guarantorAadhaarFront,
      'guarantorAadhaarBack': instance.guarantorAadhaarBack,
      'guarantorPan': instance.guarantorPan,
      'guarantorVideo': instance.guarantorVideo,
      'guarantorSignature': instance.guarantorSignature,
      'guarantorPhoto': instance.guarantorPhoto,
      'guarantorAddress': instance.guarantorAddress,
      'guarantorStatus': _$GuarantorStatusEnumMap[instance.guarantorStatus]!,
      'walletBalance': instance.walletBalance,
      'securityDeposit': instance.securityDeposit,
      'depositStatus': _$DepositStatusEnumMap[instance.depositStatus]!,
      'paymentStreak': instance.paymentStreak,
      'weeklyDistance': instance.weeklyDistance,
      'carbonSaved': instance.carbonSaved,
      'currentSpeed': instance.currentSpeed,
      'batteryPercent': instance.batteryPercent,
      'planStatus': instance.planStatus,
      'currentPlan': instance.currentPlan,
      'planStartDate': instance.planStartDate?.toIso8601String(),
      'planEndDate': instance.planEndDate?.toIso8601String(),
      'rentalStatus': instance.rentalStatus,
      'assignedVehicle': instance.assignedVehicle,
      'pickupHub': instance.pickupHub,
      'teamLeader': instance.teamLeader,
      'emergencyContact': instance.emergencyContact,
      'intent': instance.intent,
      'submissionDate': instance.submissionDate?.toIso8601String(),
      'returnPending': instance.returnPending,
      'pickupPhotoFront': instance.pickupPhotoFront,
      'pickupPhotoBack': instance.pickupPhotoBack,
      'pickupPhotoLeft': instance.pickupPhotoLeft,
      'pickupPhotoRight': instance.pickupPhotoRight,
      'pickupPhotoWithVehicle': instance.pickupPhotoWithVehicle,
      'registrationDone': instance.registrationDone,
      'depositDone': instance.depositDone,
      'kycDone': instance.kycDone,
      'planDone': instance.planDone,
      'pickupDone': instance.pickupDone,
      'accountStatus': _$AccountStatusEnumMap[instance.accountStatus]!,
      'lifecycleStatus': instance.lifecycleStatus,
      'referralCode': instance.referralCode,
      'totalRewardPoints': instance.totalRewardPoints,
      'createdAt': instance.createdAt?.toIso8601String(),
      'updatedAt': instance.updatedAt?.toIso8601String(),
    };

const _$KycStatusEnumMap = {
  KycStatus.pending: 'PENDING',
  KycStatus.draft: 'DRAFT',
  KycStatus.submitted: 'SUBMITTED',
  KycStatus.verified: 'VERIFIED',
  KycStatus.approved: 'APPROVED',
  KycStatus.rejected: 'REJECTED',
  KycStatus.infoRequired: 'INFO_REQUIRED',
  KycStatus.expired: 'EXPIRED',
};

const _$GuarantorStatusEnumMap = {
  GuarantorStatus.pending: 'PENDING',
  GuarantorStatus.draft: 'DRAFT',
  GuarantorStatus.submitted: 'SUBMITTED',
  GuarantorStatus.verified: 'VERIFIED',
  GuarantorStatus.approved: 'APPROVED',
  GuarantorStatus.rejected: 'REJECTED',
  GuarantorStatus.infoRequired: 'INFO_REQUIRED',
  GuarantorStatus.replaced: 'REPLACED',
};

const _$DepositStatusEnumMap = {
  DepositStatus.pending: 'PENDING',
  DepositStatus.notSubmitted: 'NOT_SUBMITTED',
  DepositStatus.pendingVerification: 'PENDING_VERIFICATION',
  DepositStatus.approved: 'APPROVED',
  DepositStatus.rejected: 'REJECTED',
  DepositStatus.refundRequested: 'REFUND_REQUESTED',
  DepositStatus.refunded: 'REFUNDED',
  DepositStatus.forfeited: 'FORFEITED',
  DepositStatus.partiallyRefunded: 'PARTIALLY_REFUNDED',
};

const _$AccountStatusEnumMap = {
  AccountStatus.preActive: 'PRE_ACTIVE',
  AccountStatus.active: 'ACTIVE',
  AccountStatus.suspended: 'SUSPENDED',
  AccountStatus.terminated: 'TERMINATED',
  AccountStatus.inactive: 'INACTIVE',
};
